-- منصة الأستاذ V7
-- شغّل الملف بالكامل مرة واحدة في Supabase -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'student' check(role in ('student','teacher','team')),
  student_code text unique,
  created_at timestamptz default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric(10,2) default 0,
  is_free boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  video_url text,
  pdf_path text,
  sort_order int default 0,
  created_at timestamptz default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  granted_by_code boolean default false,
  created_at timestamptz default now(),
  unique(student_id,course_id)
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role_title text not null,
  permission text not null default 'support',
  icon text default '👤',
  created_at timestamptz default now()
);

alter table public.team_members add column if not exists icon text default '👤';

create table if not exists public.progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  completed boolean default false,
  updated_at timestamptz default now(),
  unique(student_id,lesson_id)
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,full_name,student_code)
  values(new.id,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),'طالب جديد'),nullif(new.raw_user_meta_data->>'student_code',''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_teacher()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='teacher');
$$;

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;
alter table public.enrollments enable row level security;
alter table public.team_members enable row level security;
alter table public.progress enable row level security;

-- Profiles
 drop policy if exists "profiles own read" on public.profiles;
 create policy "profiles own read" on public.profiles for select using(auth.uid()=id or public.is_teacher());
 drop policy if exists "profiles own insert" on public.profiles;
 create policy "profiles own insert" on public.profiles for insert with check(auth.uid()=id and role='student');
 drop policy if exists "teacher profile update" on public.profiles;
 create policy "teacher profile update" on public.profiles for update using(public.is_teacher()) with check(public.is_teacher());

-- Courses
 drop policy if exists "courses public read" on public.courses;
 create policy "courses public read" on public.courses for select using(true);
 drop policy if exists "teacher courses insert" on public.courses;
 create policy "teacher courses insert" on public.courses for insert with check(public.is_teacher());
 drop policy if exists "teacher courses update" on public.courses;
 create policy "teacher courses update" on public.courses for update using(public.is_teacher()) with check(public.is_teacher());
 drop policy if exists "teacher courses delete" on public.courses;
 create policy "teacher courses delete" on public.courses for delete using(public.is_teacher());

-- Lessons: free-course lessons public; paid lessons only for enrolled students or teacher.
 drop policy if exists "lesson read if allowed" on public.lessons;
 create policy "lesson read if allowed" on public.lessons for select using(
   exists(select 1 from public.courses c where c.id=course_id and c.is_free=true)
   or public.is_teacher()
   or exists(select 1 from public.enrollments e where e.course_id=course_id and e.student_id=auth.uid())
 );
 drop policy if exists "teacher lessons insert" on public.lessons;
 create policy "teacher lessons insert" on public.lessons for insert with check(public.is_teacher());
 drop policy if exists "teacher lessons update" on public.lessons;
 create policy "teacher lessons update" on public.lessons for update using(public.is_teacher()) with check(public.is_teacher());
 drop policy if exists "teacher lessons delete" on public.lessons;
 create policy "teacher lessons delete" on public.lessons for delete using(public.is_teacher());

-- Enrollments
 drop policy if exists "enrollment own read" on public.enrollments;
 create policy "enrollment own read" on public.enrollments for select using(student_id=auth.uid() or public.is_teacher());
 drop policy if exists "teacher enrollment insert" on public.enrollments;
 create policy "teacher enrollment insert" on public.enrollments for insert with check(public.is_teacher());
 drop policy if exists "teacher enrollment update" on public.enrollments;
 create policy "teacher enrollment update" on public.enrollments for update using(public.is_teacher()) with check(public.is_teacher());
 drop policy if exists "teacher enrollment delete" on public.enrollments;
 create policy "teacher enrollment delete" on public.enrollments for delete using(public.is_teacher());

-- Progress
 drop policy if exists "progress own all" on public.progress;
 create policy "progress own all" on public.progress for all using(student_id=auth.uid()) with check(student_id=auth.uid());
 drop policy if exists "teacher progress read" on public.progress;
 create policy "teacher progress read" on public.progress for select using(public.is_teacher());

-- Team is public because V4 shows it on the public homepage.
 drop policy if exists "team public read" on public.team_members;
 create policy "team public read" on public.team_members for select using(true);
 drop policy if exists "team teacher insert" on public.team_members;
 create policy "team teacher insert" on public.team_members for insert with check(public.is_teacher());
 drop policy if exists "team teacher update" on public.team_members;
 create policy "team teacher update" on public.team_members for update using(public.is_teacher()) with check(public.is_teacher());
 drop policy if exists "team teacher delete" on public.team_members;
 create policy "team teacher delete" on public.team_members for delete using(public.is_teacher());

-- Starter data, only if absent.
insert into public.courses(title,description,price,is_free)
select 'كورس الكيمياء','شرح المنهج بطريقة مبسطة مع تدريبات.',300,false
where not exists(select 1 from public.courses where title='كورس الكيمياء');

insert into public.courses(title,description,price,is_free)
select 'كورس الفيزياء','شرح الدروس وحل أهم الأسئلة.',300,false
where not exists(select 1 from public.courses where title='كورس الفيزياء');

insert into public.courses(title,description,price,is_free)
select 'المراجعة المجانية','دروس مجانية للتجربة والبدء.',0,true
where not exists(select 1 from public.courses where title='المراجعة المجانية');

insert into public.team_members(name,role_title,permission,icon)
select 'الأستاذ الرئيسي','المدرس والمسؤول الرئيسي','admin','👨‍🏫'
where not exists(select 1 from public.team_members where name='الأستاذ الرئيسي');
insert into public.team_members(name,role_title,permission,icon)
select 'إدارة المنصة','إدارة الطلاب والكورسات','manager','🧑‍💼'
where not exists(select 1 from public.team_members where name='إدارة المنصة');
insert into public.team_members(name,role_title,permission,icon)
select 'الدعم الفني','مساعدة الطلاب وحل المشكلات','support','🧑‍💻'
where not exists(select 1 from public.team_members where name='الدعم الفني');

-- تفعيل المدرس بدون كتابة الإيميل في SQL. كود التفعيل: TEACHER2026
create or replace function public.activate_teacher(p_code text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if p_code <> 'TEACHER2026' then
    raise exception 'كود تفعيل المدرس غير صحيح';
  end if;
  if auth.uid() is null then
    raise exception 'يجب تسجيل الدخول أولاً';
  end if;
  update public.profiles set role='teacher' where id=auth.uid();
  if not found then
    raise exception 'لم يتم العثور على ملف الحساب';
  end if;
end;
$$;

grant execute on function public.activate_teacher(text) to authenticated;

-- لم يعد مطلوبًا كتابة إيميل المدرس في SQL.

-- تخزين فيديوهات الدروس داخل Supabase Storage (Bucket خاص).
insert into storage.buckets (id, name, public)
values ('course-videos', 'course-videos', false)
on conflict (id) do update set public=false;

drop policy if exists "course videos teacher upload" on storage.objects;
create policy "course videos teacher upload"
on storage.objects for insert to authenticated
with check (bucket_id='course-videos' and public.is_teacher());

drop policy if exists "course videos teacher update" on storage.objects;
create policy "course videos teacher update"
on storage.objects for update to authenticated
using (bucket_id='course-videos' and public.is_teacher())
with check (bucket_id='course-videos' and public.is_teacher());

drop policy if exists "course videos teacher delete" on storage.objects;
create policy "course videos teacher delete"
on storage.objects for delete to authenticated
using (bucket_id='course-videos' and public.is_teacher());

drop policy if exists "course videos allowed read" on storage.objects;
create policy "course videos allowed read"
on storage.objects for select to authenticated
using (
  bucket_id='course-videos'
  and (
    public.is_teacher()
    or exists (
      select 1 from public.enrollments e
      where e.student_id=auth.uid()
        and e.course_id=split_part(name,'/',1)::bigint
    )
    or exists (
      select 1 from public.courses c
      where c.id=split_part(name,'/',1)::bigint
        and c.is_free=true
    )
  )
);
